### ISSUE TITLE
Bug: It does not scroll vertically.

### ISSUE THREAD

**Issue by metaartisan** [rupammitra/RMShapesPageControl#1]
Bug: It does not scroll vertically.

**Comment by rupammitra** [comment]
Can I know how you are setting the current page of RMSquarePageControl? If you need a vertical page control please take the view as height greater than width, for reference you can follow my demo. Please let me know if it fixes your issue.

**Comment by rupammitra** [comment]
@metaartisan Does it solve your problem?
