### ISSUE TITLE
dot in circle

### ISSUE THREAD

**Issue by mohsinalimat** [rupammitra/RMShapesPageControl#2]
Hello,

i want to show dot in circle?

Thanks,
Mohsinali

**Comment by rupammitra** [comment]
Can you please elaborate? I didn't understand your concern.

**Comment by mohsinalimat** [comment]
page control dot in cicle not in square

**Comment by rupammitra** [comment]
Ok will give this support soon.

**Comment by rupammitra** [comment]
@mohsinalimat Feature added.
